import type {
  CaseRecord,
  ScorecardWorkbookModel,
  Step1CountryProblem,
  Step2IntermediaryAssessment,
  Step3BarrierDiagnosis,
  Step4ToolReference,
  Step5ExpansionReference,
} from "@/types/dashboard/scorecard"

export const instructionText =
  "Use Steps 1-5 to diagnose barriers, identify enabling blended finance mechanisms, and recommend global expansion pathways for each country case."

export const step1Data: Step1CountryProblem[] = [
  {
    id: "s1-kenya",
    country: "Kenya",
    sdgTarget: "SDG7 + NDC Renewable Access",
    countryChallenges: "Rural communities face high-cost, unreliable electricity access.",
    backgroundProblem: "Early-stage mini-grid developers struggle to finance feasibility work and customer acquisition.",
    existingProject: "Kenya Off-Grid Renewable Access Initiative",
    developmentRationale: "Expanding productive-use energy improves livelihoods and resilience.",
    expectedResults: "120 villages connected, 35% small business productivity uplift.",
    safeguards: "Community consultation, tariff transparency, gender inclusion plan.",
    sources: ["World Bank energy profile", "National Electrification Strategy"],
  },
  {
    id: "s1-indonesia",
    country: "Indonesia",
    sdgTarget: "SDG13 + NDC Decarbonization",
    countryChallenges: "Industrial decarbonization projects face long payback periods.",
    backgroundProblem: "Bankability is weak for clean heat retrofits in mid-sized manufacturing clusters.",
    existingProject: "Green Industry Retrofit Program",
    developmentRationale: "Reduces emissions while strengthening export competitiveness.",
    expectedResults: "15% emissions reduction across target industrial parks.",
    safeguards: "MRV protocol, labor transition planning, ESG compliance checks.",
    sources: ["UNIDO market study", "Indonesia NDC update"],
  },
  {
    id: "s1-nigeria",
    country: "Nigeria",
    sdgTarget: "SDG8 + SDG9",
    countryChallenges: "SMEs face severe FX volatility in imported equipment financing.",
    backgroundProblem: "Currency mismatch limits lender appetite for local-currency lending.",
    existingProject: "SME Productive Finance Window",
    developmentRationale: "Supports job growth and resilient domestic value chains.",
    expectedResults: "$60M equivalent local lending mobilized, 8,000 jobs supported.",
    safeguards: "Prudent FX risk limits, credit screening, anti-corruption controls.",
    sources: ["Central Bank bulletin", "IFC MSME diagnostics"],
  },
]

export const step2Data: Step2IntermediaryAssessment[] = [
  {
    id: "s2-1",
    intermediary: "Regional Development Bank of East Africa",
    type: "DFI",
    whyRelevant: "Anchor lender with local branch network and policy influence.",
    role: "Senior lender + technical convener",
    geography: "National + regional",
    relationshipStatus: "Active engagement",
    linkedCountry: "Kenya",
    linkedBarrier: "Early-stage readiness",
  },
  {
    id: "s2-2",
    intermediary: "Indonesia Clean Industry Facility",
    type: "Government-backed fund",
    whyRelevant: "Can aggregate pipeline and co-finance transition capex.",
    role: "Structured co-financier",
    geography: "National",
    relationshipStatus: "Under discussion",
    linkedCountry: "Indonesia",
    linkedBarrier: "Weak economics / long payback",
  },
  {
    id: "s2-3",
    intermediary: "West Africa Commercial Lenders Consortium",
    type: "Commercial bank consortium",
    whyRelevant: "Large SME client base but high perceived currency risk.",
    role: "Origination + senior debt",
    geography: "National",
    relationshipStatus: "New relationship",
    linkedCountry: "Nigeria",
    linkedBarrier: "FX risk",
  },
]

export const step3Data: Step3BarrierDiagnosis[] = [
  {
    id: "s3-1",
    linkedCountry: "Kenya",
    primaryBarrier: "Early-stage readiness",
    barrierDescription: "Insufficient project preparation capital and weak transaction readiness.",
    observableSigns: "Thin feasibility studies, delayed permits, fragmented demand validation.",
    projectStage: "Early Validation",
    recommendedTool: "Technical Assistance / Grants",
    source: "Internal scorecard workshop",
  },
  {
    id: "s3-2",
    linkedCountry: "Indonesia",
    primaryBarrier: "Weak economics / long payback",
    barrierDescription: "Energy transition retrofits have returns below commercial lending thresholds.",
    observableSigns: "Debt service pressure in years 1-4 and limited sponsor equity.",
    projectStage: "Pilot",
    recommendedTool: "Concessional Loan",
    source: "Industrial park financing review",
  },
  {
    id: "s3-3",
    linkedCountry: "Nigeria",
    primaryBarrier: "FX risk",
    barrierDescription: "Revenue in local currency, debt expectations in hard currency.",
    observableSigns: "Term sheets include elevated risk premium and shortened tenor.",
    projectStage: "Scale-Up",
    recommendedTool: "Hedging / Local-Currency Facility",
    source: "Lender roundtable notes",
  },
]

export const step4Data: Step4ToolReference[] = [
  {
    id: "t1",
    tool: "Technical Assistance / Grants",
    description: "Catalytic funding for project preparation, design, and ecosystem readiness.",
    bestWhen: "Projects are pre-bankability and need early diligence support.",
    strengths: ["De-risks pipeline creation", "Builds counterpart capacity"],
    weaknesses: ["Does not directly solve long-term financing need"],
    riskMethodologies: ["Readiness milestone scoring", "Capacity maturity assessment"],
    source: "OECD blended finance principles",
  },
  {
    id: "t2",
    tool: "Guarantee / Risk-Sharing",
    description: "Credit enhancement to reduce lender downside exposure.",
    bestWhen: "Commercial financiers face default or performance risk concerns.",
    strengths: ["Mobilizes private debt", "Can be targeted by segment"],
    weaknesses: ["Requires clear claim governance"],
    riskMethodologies: ["Portfolio loss distribution", "Expected shortfall stress testing"],
    source: "MDB guarantee facility guidance",
  },
  {
    id: "t3",
    tool: "First-Loss / Junior Capital",
    description: "Subordinated capital tranche absorbs initial losses to improve senior investor risk-return.",
    bestWhen: "Investor downside risk blocks senior participation.",
    strengths: ["Crowds in institutional co-investors", "Supports innovation"],
    weaknesses: ["Potentially high concessionality if poorly calibrated"],
    riskMethodologies: ["Waterfall loss simulation", "Scenario-based downside modeling"],
    source: "Convergence market reports",
  },
  {
    id: "t4",
    tool: "Concessional Loan",
    description: "Below-market debt with longer tenor or grace period to support viability.",
    bestWhen: "Economics are weak but developmental externalities are high.",
    strengths: ["Improves affordability", "Extends investment horizon"],
    weaknesses: ["Can distort market if overused"],
    riskMethodologies: ["Debt service coverage analysis", "Subsidy calibration framework"],
    source: "IFI concessionality toolkit",
  },
  {
    id: "t5",
    tool: "Hedging / Local-Currency Facility",
    description: "Mechanisms to mitigate foreign exchange mismatch and volatility.",
    bestWhen: "Revenue is local currency but financing is hard currency-linked.",
    strengths: ["Stabilizes cash flows", "Enables longer tenor lending"],
    weaknesses: ["Can carry significant premium in thin markets"],
    riskMethodologies: ["FX VaR analysis", "Currency stress scenarios"],
    source: "TCX and local currency facility guidance",
  },
  {
    id: "t6",
    tool: "Outcome-Based Incentives",
    description: "Payments tied to verified social or environmental outcomes.",
    bestWhen: "Impact value exists but is hard to monetize through core revenues.",
    strengths: ["Aligns incentives with measurable results", "Improves impact credibility"],
    weaknesses: ["Requires robust MRV and verification infrastructure"],
    riskMethodologies: ["Outcome attribution quality checks", "Verification risk audits"],
    source: "Results-based financing playbook",
  },
]

export const step5Data: Step5ExpansionReference[] = [
  {
    id: "e1",
    model: "Deepen Local",
    description: "Scale depth in one market through ecosystem density and stronger local institutions.",
    bestWhen: "Regulatory complexity and local trust are decisive for impact.",
    pros: ["High contextual fit", "Strong stakeholder ownership"],
    cons: ["Slower geographic diversification"],
    implementationImplications: "Invest in local governance, talent, and partner pipelines.",
  },
  {
    id: "e2",
    model: "Local Repurposing",
    description: "Adapt a proven model for adjacent sectors or customer segments in-country.",
    bestWhen: "Core infrastructure exists but demand needs customization.",
    pros: ["Cost-efficient reuse", "Faster than greenfield"],
    cons: ["May face legacy constraints"],
    implementationImplications: "Run structured design sprints with local implementation teams.",
  },
  {
    id: "e3",
    model: "New Build",
    description: "Create a new platform in a new geography with full operating setup.",
    bestWhen: "Untapped market potential is large and first-mover advantage matters.",
    pros: ["Full design freedom", "Potentially large scale"],
    cons: ["Higher capex and execution risk"],
    implementationImplications: "Requires robust market entry diligence and regulatory structuring.",
  },
  {
    id: "e4",
    model: "Local Hybrid",
    description: "Combine local partnership infrastructure with selective imported capabilities.",
    bestWhen: "Need balance between speed and contextual legitimacy.",
    pros: ["Balanced risk profile", "Adaptive operations"],
    cons: ["Coordination complexity"],
    implementationImplications: "Strong partner governance and shared KPI architecture required.",
  },
  {
    id: "e5",
    model: "Hybrid",
    description: "Multi-country blended operating model with centralized backbone and local delivery nodes.",
    bestWhen: "Regional scale and cross-market learning are strategic priorities.",
    pros: ["High scalability", "Knowledge transfer across markets"],
    cons: ["Higher management complexity"],
    implementationImplications: "Set up central PMO, modular playbooks, and cross-country controls.",
  },
]

export const mockCases: CaseRecord[] = [
  {
    id: "case-ke-1",
    country: step1Data[0],
    intermediary: step2Data[0],
    barrier: step3Data[0],
    expansionModel: step5Data[3],
    recommendationProfile: {
      localOwnershipNeed: 8,
      speedPriority: 6,
      costSensitivity: 7,
      capacityBuildingNeed: 9,
      scalabilityGoal: 7,
      regulatoryFeasibilityNeed: 8,
    },
  },
  {
    id: "case-id-1",
    country: step1Data[1],
    intermediary: step2Data[1],
    barrier: step3Data[1],
    expansionModel: step5Data[1],
    recommendationProfile: {
      localOwnershipNeed: 6,
      speedPriority: 7,
      costSensitivity: 8,
      capacityBuildingNeed: 7,
      scalabilityGoal: 8,
      regulatoryFeasibilityNeed: 7,
    },
  },
  {
    id: "case-ng-1",
    country: step1Data[2],
    intermediary: step2Data[2],
    barrier: step3Data[2],
    expansionModel: step5Data[4],
    recommendationProfile: {
      localOwnershipNeed: 7,
      speedPriority: 8,
      costSensitivity: 8,
      capacityBuildingNeed: 6,
      scalabilityGoal: 9,
      regulatoryFeasibilityNeed: 6,
    },
  },
]

export const mockWorkbook: ScorecardWorkbookModel = {
  instruction: instructionText,
  step1: step1Data,
  step2: step2Data,
  step3: step3Data,
  step4: step4Data,
  step5: step5Data,
  cases: mockCases,
}
